#!/bin/bash

THIS_DIR=`pwd`
rm -rf $HOME/.vim

function unlinkToHome {
 if [ -L $HOME/$1 ]; then
    echo "Removing link " $HOME/$1
    rm $HOME/$1
 fi
}

unlinkToHome .vimrc
unlinkToHome .zshrc
unlinkToHome .juliarc.jl
unlinkToHome .atom

