### Project specific config ###
language: python

env:
  global:
    - APM_TEST_PACKAGES=""
    - ATOM_LINT_WITH_BUNDLED_NODE="true"

jobs:
  include:
    - os: linux
      python: 3.7
      env: ATOM_CHANNEL=stable
    - os: linux
      python: 3.7
      env: ATOM_CHANNEL=beta
    - os: osx
      language: generic
      env: ATOM_CHANNEL=stable
    - os: osx
      language: generic
      env: ATOM_CHANNEL=beta


before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cd /usr/local/bin && mv python python.old && ln -s python3 python && cd -; fi

### Generic setup follows ###
script:
  - pip3 install jedi
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

git:
  depth: 10

sudo: false

dist: bionic

addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev
