name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: ${{ matrix.os }} - Atom ${{ matrix.atom_channel }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
        atom_channel: [stable, beta]
    steps:
      - uses: actions/checkout@v2
      - uses: atom-community/action-setup-atom@v1
        with:
          channel: ${{ matrix.atom_channel }}

      - name: Install dependencies
        run: |
          apm install --production
          npm install --only=dev

      # The tests are flaky
      - name: Run tests
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 1
          max_attempts: 3
          command: npm run test

  Lint:
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, 'Prepare ')"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Commit lint ✨
        uses: wagoid/commitlint-github-action@v2

      - name: Setup Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format ✨
        run: pnpm run test.format

      - name: Lint
        run: pnpm run test.lint
